AWSTemplateFormatVersion: '2010-09-09'
Description: Removes all Infra from Budget - likely due to cost breach
Conditions:
  Never:
    !Equals [ "A", "B" ]
Resources:
  NonResource:
    Type: Custom::NonResource
    Condition: Never